title: Dokumentation
description: Dokumentation f√ºr SOLECTRUS
theme: just-the-docs

url: https://docs.solectrus.de

aux_links:
  SOLECTRUS: https://solectrus.de

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: 'Diese Seite auf GitHub bearbeiten.'
gh_edit_repository: 'https://github.com/solectrus/docs' # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

callouts:
  highlight:
    title: Highlight
    color: yellow

  important:
    title: Wichtig
    color: blue

  new:
    title: Neu
    color: green

  note:
    title: Hinweis
    color: purple

  warning:
    title: Warnung
    color: red

sass:
  quiet_deps: true
